version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - JWT_SECRET=mySecretKey123456789012345678901234567890
    depends_on:
      - postgres
    networks:
      - translation-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=translation_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - translation-network

volumes:
  postgres_data:

networks:
  translation-network::

networks:
  translation-network:
    driver: bridge
